uploads = []
outputs = []

[[generated]]
id = "LbgEVxND56JHYnNmWeMCZ"
uri = "file://artifacts/shpe-utd/src/assets/images/hero.png"
type = "image"
title = "diverse engineering students campus"

[[generated]]
id = "6ory4i6gx9IdddWkXjTWP"
uri = "file://artifacts/shpe-utd/src/assets/images/event-1.png"
type = "image"
title = "students in workshop setting"

[[generated]]
id = "J9E3r_GWa-c6WatL0R8r3"
uri = "file://artifacts/shpe-utd/src/assets/images/event-2.png"
type = "image"
title = "students at networking event"

[[generated]]
id = "qK3YBFzo5-WhkcJ9oY9Kk"
uri = "file://artifacts/shpe-utd/src/assets/images/event-3.png"
type = "image"
title = "students at panel discussion"

[[generated]]
id = "oR5cnHJOUNae8hbk1Qfty"
uri = "file://artifacts/shpe-utd/src/assets/images/event-4.png"
type = "image"
title = "students at social gathering"

[[generated]]
id = "a2PhS0TjmjdxWqCLyTiC5"
uri = "file://artifacts/shpe-utd/src/assets/images/about.png"
type = "image"
title = "students at engineering event"
